name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4

      # Login to Azure using service principal
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

      # Log in to ACR
      - name: Azure Container Registry Login
        run: az acr login --name ${{ secrets.ACR_NAME }}

      # Build and Push Docker image to ACR
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.ACR_NAME }}.azurecr.io/spring-boot-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - name: Deploy via SSH to Azure VM
        uses: appleboy/ssh-action@v1.20
        with:
          host: ${{ secrets.AZURE_VM_HOST }}          # Public IP/DNS of your Azure VM
          username: azureuser                         # Default user for Azure VMs
          key: ${{ secrets.AZURE_VM_SSH_KEY }}        # Private key stored in GitHub Secrets
          script: |
            cd /path/to/your/app                      # Go to your app folder
            docker compose pull
            docker compose up -d --force-recreate

